/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author Erik
 */
public class FrmPrincipal extends javax.swing.JFrame implements IContenedorPrincipal {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public FrmPrincipal() {
        initComponents();
        
        mostrarPanel(new PnlSwipe());
    }
    
    public void mostrarPanel(javax.swing.JPanel panel) {
        jPanel2.setLayout(new java.awt.BorderLayout());
        
        jPanel2.removeAll();
        
        jPanel2.add(panel, java.awt.BorderLayout.CENTER);
        
        jPanel2.revalidate();
        jPanel2.repaint();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSwipe = new javax.swing.JButton();
        btnMensajes = new javax.swing.JButton();
        btnParejaIdeal = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnConfiguracion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 213, 233));

        btnSwipe.setBackground(new java.awt.Color(255, 213, 233));
        btnSwipe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSwipe.setForeground(new java.awt.Color(102, 0, 51));
        btnSwipe.setText("SWIPE");
        btnSwipe.setBorderPainted(false);
        btnSwipe.addActionListener(this::btnSwipeActionPerformed);

        btnMensajes.setBackground(new java.awt.Color(255, 213, 233));
        btnMensajes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMensajes.setForeground(new java.awt.Color(102, 0, 51));
        btnMensajes.setText("MENSAJES");
        btnMensajes.setBorderPainted(false);
        btnMensajes.addActionListener(this::btnMensajesActionPerformed);

        btnParejaIdeal.setBackground(new java.awt.Color(255, 213, 233));
        btnParejaIdeal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnParejaIdeal.setForeground(new java.awt.Color(102, 0, 51));
        btnParejaIdeal.setText("PAREJA IDEAL");
        btnParejaIdeal.setBorderPainted(false);
        btnParejaIdeal.addActionListener(this::btnParejaIdealActionPerformed);

        btnUsuario.setBackground(new java.awt.Color(255, 213, 233));
        btnUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUsuario.setForeground(new java.awt.Color(102, 0, 51));
        btnUsuario.setText("USUARIO");
        btnUsuario.setBorderPainted(false);
        btnUsuario.addActionListener(this::btnUsuarioActionPerformed);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RIZZMEUPLOGO.png"))); // NOI18N

        btnConfiguracion.setBackground(new java.awt.Color(255, 213, 233));
        btnConfiguracion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConfiguracion.setForeground(new java.awt.Color(102, 0, 51));
        btnConfiguracion.setText("CONFIGURACION");
        btnConfiguracion.setBorderPainted(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMensajes)
                        .addGap(63, 63, 63))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnParejaIdeal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSwipe)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnUsuario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnConfiguracion)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addComponent(btnSwipe)
                .addGap(18, 18, 18)
                .addComponent(btnMensajes)
                .addGap(18, 18, 18)
                .addComponent(btnParejaIdeal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284, Short.MAX_VALUE)
                .addComponent(btnUsuario)
                .addGap(78, 78, 78))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(404, Short.MAX_VALUE)
                    .addComponent(btnConfiguracion)
                    .addGap(334, 334, 334)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 770));

        jPanel2.setBackground(new java.awt.Color(228, 114, 159));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 860, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSwipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwipeActionPerformed
        // TODO add your handling code here:
        mostrarPanel(new PnlSwipe());
    }//GEN-LAST:event_btnSwipeActionPerformed

    private void btnMensajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensajesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMensajesActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // TODO add your handling code here:
        mostrarPanel(new PnlPerfilUsuario());
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnParejaIdealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParejaIdealActionPerformed
        mostrarPanel(new PnlParejaIdeal());
    }//GEN-LAST:event_btnParejaIdealActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnMensajes;
    private javax.swing.JButton btnParejaIdeal;
    private javax.swing.JButton btnSwipe;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
