/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.SwingConstants;

/**
 *
 * @author Roger Jr
 */
public class FrmConfirmacionReporte extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmConfirmacionReporte.class.getName());
    
    private static final Color COLOR_FONDO = new Color(255, 220, 235);
    private static final Color COLOR_TEXTO = new Color(102, 0, 51);
    private static final Color COLOR_BTN = new Color(80, 80, 80);

    private final boolean exitoso;
    private final String mensaje;

    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JButton btnCerrar;

    /**
     * Creates new form FrmConfirmacionReporte
     */
    public FrmConfirmacionReporte(java.awt.Frame parent,
            boolean exitoso,
            String mensaje) {
        super(parent, true);
        this.exitoso = exitoso;
        this.mensaje = mensaje;
        initVista();
        initEventos();
    }
    // </editor-fold>
    

    private void initVista()
    {
        setDefaultCloseOperation(
                javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confirmacion");
        setResizable(false);
        setSize(340, 240);
        setLocationRelativeTo(getParent());
        setUndecorated(true);

        pnlPrincipal = new javax.swing.JPanel();
        pnlPrincipal.setBackground(COLOR_FONDO);
        pnlPrincipal.setBorder(
                BorderFactory.createLineBorder(
                        new Color(200, 150, 170), 1));
        pnlPrincipal.setLayout(null);

        // icono segun resultado
        lblIcono = new javax.swing.JLabel();
        lblIcono.setFont(new Font("Segoe UI", Font.PLAIN, 48));
        lblIcono.setHorizontalAlignment(SwingConstants.CENTER);

        if (exitoso)
        {
            // check verde para reporte exitoso
            lblIcono.setText("✔");
            lblIcono.setForeground(new Color(0, 160, 80));
        }
        else
        {
            // triangulo de advertencia para reporte duplicado
            lblIcono.setText("⚠");
            lblIcono.setForeground(new Color(200, 120, 0));
        }

        lblIcono.setBounds(0, 30, 340, 60);
        pnlPrincipal.add(lblIcono);

        // mensaje principal
        lblMensaje = new javax.swing.JLabel(
                "<html><div style='text-align:center;'>"
                + mensaje
                + "</div></html>");
        lblMensaje.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblMensaje.setForeground(COLOR_TEXTO);
        lblMensaje.setHorizontalAlignment(SwingConstants.CENTER);
        lblMensaje.setBounds(20, 105, 300, 50);
        pnlPrincipal.add(lblMensaje);

        // boton cerrar
        btnCerrar = new javax.swing.JButton("Cerrar");
        btnCerrar.setBackground(COLOR_BTN);
        btnCerrar.setForeground(Color.WHITE);
        btnCerrar.setFont(new Font("Segoe UI", Font.BOLD, 13));
        btnCerrar.setBorderPainted(false);
        btnCerrar.setFocusPainted(false);
        btnCerrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCerrar.setBounds(110, 175, 120, 36);
        pnlPrincipal.add(btnCerrar);

        setContentPane(pnlPrincipal);
    }

    private void initEventos()
    {
        btnCerrar.addActionListener(e -> dispose());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
