/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.util.logging.Logger;
import javax.swing.SwingConstants;

/**
 *
 * @author Roger Jr
 */
public class FrmExitoEvaluacion extends javax.swing.JPanel {
private static final Logger logger = Logger.getLogger(
            FrmExitoEvaluacion.class.getName());

    private static final Color COLOR_FONDO = new Color(255, 235, 245);
    private static final Color COLOR_TEXTO = new Color(102, 0, 51);
    private static final Color COLOR_BTN = new Color(80, 80, 80);
    

    private final IContenedorPrincipal padre;

    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JButton btnCerrar;

    public FrmExitoEvaluacion(IContenedorPrincipal  padre)
    {
        this.padre = padre;
        initVista();
        initEventos();
    }
    // </editor-fold>


    private void initVista()
    {
        setBackground(COLOR_FONDO);
        setLayout(null);
        setPreferredSize(new Dimension(860, 770));

        // icono check verde
        lblIcono = new javax.swing.JLabel("✔");
        lblIcono.setFont(new Font("Segoe UI", Font.PLAIN, 72));
        lblIcono.setForeground(new Color(0, 160, 80));
        lblIcono.setHorizontalAlignment(SwingConstants.CENTER);
        lblIcono.setBounds(0, 260, 860, 100);
        add(lblIcono);

        // mensaje de exito
        lblMensaje = new javax.swing.JLabel(
                "<html><div style='text-align:center;'>"
                + "Reporte evaluado correctamente"
                + "</div></html>");
        lblMensaje.setFont(new Font("Segoe UI", Font.PLAIN, 22));
        lblMensaje.setForeground(COLOR_TEXTO);
        lblMensaje.setHorizontalAlignment(SwingConstants.CENTER);
        lblMensaje.setBounds(0, 375, 860, 50);
        add(lblMensaje);

        // boton para volver a la bandeja
        btnCerrar = new javax.swing.JButton("Volver a reportes");
        btnCerrar.setBackground(COLOR_BTN);
        btnCerrar.setForeground(Color.WHITE);
        btnCerrar.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnCerrar.setBorderPainted(false);
        btnCerrar.setFocusPainted(false);
        btnCerrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCerrar.setBounds(330, 450, 200, 42);
        add(btnCerrar);
    }

    // evento del boton
    private void initEventos() {
        btnCerrar.addActionListener(e
                -> {
            if (padre != null) {
                padre.mostrarPanel(new FrmBandejaReportes());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
