/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import dto.UsuarioDTO;
import dto.LikeDTO;
import explorarperfiles.IExplorarPerfiles;
import explorarperfiles.ExplorarPerfiles;
import java.time.LocalDateTime;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
/**
 *
 * @author Erik
 */
public class PnlParejaIdeal extends javax.swing.JPanel {

    private IExplorarPerfiles negocioExplorar;
    private UsuarioDTO candidatoActual;
    /**
     * Creates new form PnlParejaIdeal
     */
    public PnlParejaIdeal() {
        initComponents();
    }
    
    private void cargarPerfilFiltradoMock() {
        // Se asume que el ID del usuario logueado es 1L para la prueba
        List<UsuarioDTO> candidatos = negocioExplorar.obtenerCandidatosFiltrados(1L);
        
        if (candidatos != null && !candidatos.isEmpty()) {
            candidatoActual = candidatos.get(0);
            
            // Llenar los labels con los datos del DTO
            lblNombreEdad2.setText(candidatoActual.getNombre() + ", " + candidatoActual.getEdad());
            
            if (candidatoActual.getProfesion() != null) {
                lblProfesion.setText(candidatoActual.getProfesion());
            } else {
                lblProfesion.setText("Estudiante");
            }
            
            lblDescripcion.setText(candidatoActual.getDescripcionPersonal());
        }
    }

    private void configurarAccionesBotones() {
        btnRizz.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (candidatoActual != null) {
                    LikeDTO like = new LikeDTO(null, 1L, candidatoActual.getId(), true, LocalDateTime.now());
                    negocioExplorar.registrarLike(like);
                }
            }
        });

        btnSaltar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (candidatoActual != null) {
                    LikeDTO skip = new LikeDTO(null, 1L, candidatoActual.getId(), false, LocalDateTime.now());
                    negocioExplorar.registrarLike(skip);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInfoContenedor = new javax.swing.JPanel();
        lblNombreEdad = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblNombreEdad2 = new javax.swing.JLabel();
        lblProfesion = new javax.swing.JLabel();
        btnSaltar = new javax.swing.JButton();
        btnRizz = new javax.swing.JButton();
        contenedorEtiquetas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlFotoContenedor = new javax.swing.JPanel();

        setBackground(new java.awt.Color(228, 114, 159));
        setPreferredSize(new java.awt.Dimension(860, 770));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlInfoContenedor.setBackground(new java.awt.Color(255, 213, 233));

        lblNombreEdad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombreEdad.setForeground(new java.awt.Color(47, 21, 37));

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(47, 21, 37));
        lblDescripcion.setText("Descripcion");

        lblNombreEdad2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombreEdad2.setForeground(new java.awt.Color(47, 21, 37));
        lblNombreEdad2.setText("Nombre, Edad");

        lblProfesion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblProfesion.setForeground(new java.awt.Color(47, 21, 37));
        lblProfesion.setText("Profesion");

        btnSaltar.setBackground(new java.awt.Color(255, 169, 217));
        btnSaltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSaltar.setText("SALTAR");
        btnSaltar.setBorderPainted(false);

        btnRizz.setBackground(new java.awt.Color(255, 51, 153));
        btnRizz.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRizz.setText("RIZZ ME UP!");
        btnRizz.setBorderPainted(false);

        contenedorEtiquetas.setBackground(new java.awt.Color(238, 197, 217));

        jLabel1.setBackground(new java.awt.Color(55, 28, 45));
        jLabel1.setForeground(new java.awt.Color(55, 28, 45));
        jLabel1.setText("ETIQUETA 1");
        contenedorEtiquetas.add(jLabel1);

        jLabel2.setForeground(new java.awt.Color(55, 28, 45));
        jLabel2.setText("ETIQUETA 2");
        contenedorEtiquetas.add(jLabel2);

        jLabel3.setForeground(new java.awt.Color(55, 28, 45));
        jLabel3.setText("ETIQUETA 3");
        contenedorEtiquetas.add(jLabel3);

        javax.swing.GroupLayout pnlInfoContenedorLayout = new javax.swing.GroupLayout(pnlInfoContenedor);
        pnlInfoContenedor.setLayout(pnlInfoContenedorLayout);
        pnlInfoContenedorLayout.setHorizontalGroup(
            pnlInfoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoContenedorLayout.createSequentialGroup()
                .addGroup(pnlInfoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlInfoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlInfoContenedorLayout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(pnlInfoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNombreEdad2)
                                .addGroup(pnlInfoContenedorLayout.createSequentialGroup()
                                    .addComponent(lblNombreEdad)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(contenedorEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(pnlInfoContenedorLayout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(pnlInfoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblProfesion)
                                .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInfoContenedorLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnSaltar)
                        .addGap(41, 41, 41)
                        .addComponent(btnRizz)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlInfoContenedorLayout.setVerticalGroup(
            pnlInfoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoContenedorLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblNombreEdad2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProfesion)
                .addGroup(pnlInfoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfoContenedorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contenedorEtiquetas, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                    .addGroup(pnlInfoContenedorLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblNombreEdad)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRizz)
                    .addComponent(btnSaltar))
                .addGap(16, 16, 16))
        );

        add(pnlInfoContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 350, 230));

        pnlFotoContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnlFotoContenedor.setPreferredSize(new java.awt.Dimension(350, 350));

        javax.swing.GroupLayout pnlFotoContenedorLayout = new javax.swing.GroupLayout(pnlFotoContenedor);
        pnlFotoContenedor.setLayout(pnlFotoContenedorLayout);
        pnlFotoContenedorLayout.setHorizontalGroup(
            pnlFotoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        pnlFotoContenedorLayout.setVerticalGroup(
            pnlFotoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        add(pnlFotoContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 350, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRizz;
    private javax.swing.JButton btnSaltar;
    private javax.swing.JPanel contenedorEtiquetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombreEdad;
    private javax.swing.JLabel lblNombreEdad2;
    private javax.swing.JLabel lblProfesion;
    private javax.swing.JPanel pnlFotoContenedor;
    private javax.swing.JPanel pnlInfoContenedor;
    // End of variables declaration//GEN-END:variables
}
